### ISSUE TITLE
SS 4.4 error

### ISSUE THREAD

**Issue by RVXD** [axllent/silverstripe-image-optimiser#2]
With SS 4.4. the module gives this error:
PHP Fatal error:  Cannot redeclare non static SilverStripe\\Dev\\BuildTask::$enabled as static Axllent\\ImageOptimiser\\Tasks\\ImageOptimiserTask::$enabled in /httpdocs/vendor/axllent/silverstripe-image-optimiser/src/Tasks/ImageOptimiserTask.php on line 26

If you remove private static $enabled = false; from ImageOptimizerTask line 59 the error is gone.
Not sure if the $enabled = false is still needed.

**Comment by RVXD** [comment]
It should be:
protected $enabled = false;

**Comment by axllent** [comment]
Thanks Remy, that was a stupid mistake...! Fixed now.
