### ISSUE TITLE
Not working in uploadfield

### ISSUE THREAD

**Issue by mi32dogs** [axllent/silverstripe-image-optimiser#3]
Hi it works fine if I upload images via the file system, but if I use a uploadfield in a page or dataobject it does not seem to work, anything I need to do to make it work in uploadfields?

**Comment by axllent** [comment]
Hi @mi32dogs. You shouldn't have to do anything. I have just installed a fresh plain SilverStripe project to test, added an `Image` field to `Page`, and the result is as follows:

![Peek 2020-05-14 14-23](https://user-images.githubusercontent.com/1463435/81885566-b171c600-95ee-11ea-8c7e-e7a088f41444.gif)

**Comment by mi32dogs** [comment]
Yes, sorry i found out that nomidi/silverstripe-webp-image and your module are having some issue's together. i have added the WebP image part to your module so it now optimise, compress and generates WebP images from new and resampled images, you wand me to send you a copy so you can add the WebP part onto yours?

**Comment by axllent** [comment]
If you have your modified code in a repo then I'll have a look if you give me the link, although I cannot promise I'll merge it in as these are really serving two different purposes. Mine optimises the source and generated images in their original formats, the other module changes the generated format to webp
