### ISSUE TITLE
Errors when uploading from a front end form

### ISSUE THREAD

**Issue by polycode-nz** [axllent/silverstripe-image-optimiser#4]
Works perfectly when uploading through the cms admin area.

When uploading via a front end form I get these two errors:

```
[Warning] copy(): Filename cannot be empty
POST /submission/SubmissionForm/
Line 110 in /var/www/html/vendor/axllent/silverstripe-image-optimiser/src/Flysystem/FlysystemAssetStore.php
```

And 

```
[Emergency] Uncaught InvalidArgumentException: `/tmp/silverstripe-cache-php7.1.33-var-www-html/www-data/optim_60393a8b449d4.` does not exist
POST /submission/SubmissionForm/
Line 14 in /var/www/html/vendor/spatie/image-optimizer/src/Image.php
```

The image does get uploaded.

Code I'm using:

```
for ($i = 0; $i < $num; $i++)
{
	# Group by field
	$_FILES['Attachment'.$i]['name'] = $_files['Attachment']['name'][$i];
	$_FILES['Attachment'.$i]['type'] = $_files['Attachment']['type'][$i];
	$_FILES['Attachment'.$i]['size'] = $_files['Attachment']['size'][$i];
	$_FILES['Attachment'.$i]['error'] = $_files['Attachment']['error'][$i];
	$_FILES['Attachment'.$i]['tmp_name'] = $_files['Attachment']['tmp_name'][$i];
}

foreach ($_FILES as $field_name => $attachment)
{
	$file = File::create();
	$upload = Upload::create();
	$upload->loadIntoFile($attachment, $file, '/Submission attachments');

	$test = Attachment::create();
	$test->Title = $attachment['name'];
	$test->FileID = $upload->getFile()->ID;

	$submission->Attachment()->add($test);

	AssetAdmin::singleton()->generateThumbnails($file);
}
```

**Comment by axllent** [comment]
I don't really understand what your `Upload` class is here (its not part of Silverstripe core modules), nor what its `loadInfoFile()` function does, so I can't see how/if fields like the filename get defined properly.

I manually create files similar to this (which works with the image optimiser):

```php
$folder = Folder::find_or_make("Test"); // or whatever your parent folder name is
$file = File::create(
    [
        'ParentID' => $folder->ID,
        'Name'     => $filename,
    ]
);
$file->setFromLocalFile(
    $tmp_name,
    $folder->Name . '/' . $filename
);
$file->write();
..... // publish etc
```
I'm not sure that helps?

**Comment by polycode-nz** [comment]
`Upload` is from `use SilverStripe\Assets\Upload;` and is for uploading a file. 

I may be miss understanding, your example doesn't look like it would upload the file or has already happened? Where were `$filename` and `$tmp_name` set?

The function:

```
/**
 * Save an file passed from a form post into this object.
 * File names are filtered through {@link FileNameFilter}, see class documentation
 * on how to influence this behaviour.
 *
 * @param array $tmpFile
 * @param AssetContainer $file
 * @param string|bool $folderPath
 * @return bool True if the file was successfully saved into this record
 * @throws Exception
 */
public function loadIntoFile($tmpFile, $file = null, $folderPath = false)
{
    $this->file = $file;

    // Validate filename
    $filename = $this->getValidFilename($tmpFile, $folderPath);
    if (!$filename) {
        return false;
    }
    $filename = $this->resolveExistingFile($filename);

    // Save changes to underlying record (if it's a DataObject)
    $this->storeTempFile($tmpFile, $filename, $this->file);
    if ($this->file instanceof DataObject) {
        $this->file->write();
    }

    //to allow extensions to e.g. create a version after an upload
    $this->file->extend('onAfterUpload');
    $this->extend('onAfterLoadIntoFile', $this->file);
    return true;
}
```

**Comment by axllent** [comment]
Ahh, sorry for the confusion. I assumed that your `Upload` was a model (and not a controller) in your example. 

In my example the upload has already happened - so you're manually looping though the `$_FILES` variables as per your first example. Both `$filename` and `$tmp_name` would be from the `$_FILES` array - I was just trying to keep my example simple), and `Upload:class` isn't used at all.

**Comment by polycode-nz** [comment]
All good. Yeah I am. Use case is dynamic/unknown amount of file uploads so having to upload it manually.

This seems to have fixed itself somehow now. Files are there and optimised no errors or warnings.

**Comment by axllent** [comment]
Strange that it has fixed itself somehow, but all good! Anyway, for what it is worth, I have used modules like [this](https://github.com/jinjie/silverstripe-frontenduploadfield) in the past which deal with several aspects, however I tend to stay away from frontend uploads where possible, and in the one case I use it heavily it's an API of sorts, so I deal with the uploads completely manually using the default $_POST and PHP file handling, and then just write the Image (or File) as I explained above.
